# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(705, 841)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.console_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.console_browser.setGeometry(QtCore.QRect(20, 460, 661, 321))
        self.console_browser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.console_browser.setObjectName("console_browser")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(80, 80, 191, 221))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 189, 219))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 131, 80))
        self.groupBox.setObjectName("groupBox")
        self.smooth_combo = QtWidgets.QComboBox(self.groupBox)
        self.smooth_combo.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.smooth_combo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.smooth_combo.setObjectName("smooth_combo")
        self.smooth_combo.addItem("")
        self.smooth_combo.addItem("")
        self.smooth_combo.addItem("")
        self.data_proc_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.data_proc_button.setGeometry(QtCore.QRect(40, 130, 93, 31))
        self.data_proc_button.setObjectName("data_proc_button")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(430, 80, 191, 221))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 189, 219))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 30, 121, 81))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setObjectName("groupBox_2")
        self.filename_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.filename_edit.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.filename_edit.setObjectName("filename_edit")
        self.generate_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.generate_button.setGeometry(QtCore.QRect(40, 130, 91, 31))
        self.generate_button.setObjectName("generate_button")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 172, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 23))
        self.menubar.setObjectName("menubar")
        self.menuF = QtWidgets.QMenu(self.menubar)
        self.menuF.setObjectName("menuF")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.action_openfolder = QtWidgets.QAction(mainWindow)
        self.action_openfolder.setObjectName("action_openfolder")
        self.action_exit = QtWidgets.QAction(mainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_3D_Preview = QtWidgets.QAction(mainWindow)
        self.action_3D_Preview.setObjectName("action_3D_Preview")
        self.menuF.addAction(self.action_openfolder)
        self.menuF.addAction(self.action_exit)
        self.menubar.addAction(self.menuF.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(mainWindow)
        self.smooth_combo.activated['int'].connect(mainWindow.get_smooth)
        self.data_proc_button.clicked.connect(mainWindow.data_proc)
        self.generate_button.clicked.connect(mainWindow.generate_stl)
        self.action_openfolder.triggered['bool'].connect(mainWindow.get_path)
        self.action_exit.triggered['bool'].connect(mainWindow.close)
        self.action_3D_Preview.triggered['bool'].connect(mainWindow.preview_3D)
        self.pushButton.clicked.connect(mainWindow.preview_3D)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "STL文件生成工具"))
        self.groupBox.setTitle(_translate("mainWindow", "选择平滑方式"))
        self.smooth_combo.setItemText(0, _translate("mainWindow", "No_Smooth"))
        self.smooth_combo.setItemText(1, _translate("mainWindow", "2D_Smooth"))
        self.smooth_combo.setItemText(2, _translate("mainWindow", "3D_Smooth"))
        self.data_proc_button.setText(_translate("mainWindow", "数据处理"))
        self.groupBox_2.setTitle(_translate("mainWindow", "输入stl文件名"))
        self.generate_button.setText(_translate("mainWindow", "生成stl文件"))
        self.pushButton.setText(_translate("mainWindow", "预览stl文件"))
        self.menuF.setTitle(_translate("mainWindow", "File"))
        self.menuView.setTitle(_translate("mainWindow", "View"))
        self.action_openfolder.setText(_translate("mainWindow", "open folder"))
        self.action_exit.setText(_translate("mainWindow", "exit"))
        self.action_3D_Preview.setText(_translate("mainWindow", "3D_Preview"))

